airquality:
  target: ci
  outputs:
    ci:
      type: athena
      s3_staging_dir: s3://airquality-lake-338534047403/athena-results/
      s3_data_dir: s3://airquality-lake-338534047403/curated_ci/
      region_name: eu-north-1
      database: awsdatacatalog
      schema: airquality_ci
      threads: 4
