name: dbt CI

on:
  pull_request:
    paths:
      - 'transform/**'
      - '.github/workflows/ci.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: transform
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dbt
        run: pip install dbt-athena-community==1.11.1
      - name: dbt deps
        run: dbt deps --profiles-dir ci
      - name: dbt build
        run: dbt build --profiles-dir ci
